# Generated by Django 3.2 on 2022-01-16 10:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20220110_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
