# Generated by Django 3.2 on 2022-01-17 06:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dweuirck0/image/upload/v1642159233/sample.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
