# Generated by Django 3.2 on 2022-01-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220110_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Ordered', 'Ordered')], default='Pending', max_length=60),
        ),
    ]
